FROM node:20-bookworm-slim AS storybook
WORKDIR /app

ENV NODE_TLS_REJECT_UNAUTHORIZED=0
RUN npm config set registry https://registry.npmjs.org/
RUN npm config set strict-ssl false

RUN apt-get update && apt-get install -y xdg-utils && rm -rf /var/lib/apt/lists/*

COPY package.json package-lock.json ./
RUN npm ci --no-audit --no-fund --legacy-peer-deps

COPY . .

EXPOSE 6006

CMD ["npm", "run", "storybook"]
